version: 2.1

orbs:
  go: circleci/go@1.7.0

jobs:
  test:
    working_directory: /go/src/github.com/goccy/go-yaml
    parameters:
      go-version:
        type: string
    executor:
      name: go/default
      tag: << parameters.go-version >>
    steps:
      - checkout
      - run:
          name: merge base branch
          command: |
            git remote add goccy https://github.com/goccy/go-yaml.git
            git pull goccy master
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Run unit tests and measure coverage
          command: |
            go test -v -coverprofile=coverage.out ./...
            bash <(curl -s https://codecov.io/bash) -P ${CIRCLE_PULL_REQUEST##*/}
workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              go-version:
                - '1.16'
                - '1.15'
